server:
  port: "8080"

postgres:
  host: localhost
  port: "5433"
  username: postgres
  password: ${DB_PASSWORD}
  database: postgres
  sslmode: disable

  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300
